### PR TITLE
Llvm Cmakefile and minor changes.

### PR DESCRIPTION
**Pull request by Ebiroll**

### CODE REVIEW

**Comment by marcusz** [comment]
Hi! Thank's for the pull request! It looks like you're PR is aiming at master-branch when it is really a small update to the llvm-branch. You are asking to merge 362 commits. Can you make a new PR towards the llvm branch instead? Or do I misunderstand?

**Comment by Ebiroll** [comment]
Hmmm. I am not sure how to do this correctly. This is what I see, and I can pull  the changes of my llvm branch from github, but cannot make a pull request..
 git branch -a
* llvm
  master
  remotes/origin/HEAD -> origin/master
  remotes/origin/bc2
  remotes/origin/core-api
  remotes/origin/llvm
 ...
I will just remove this pull request and try again.

**Comment by Ebiroll** [comment]
I dont understand how to do it.
My changes however are these: https://github.com/marcusz/floyd/pull/79/commits/0a5fbe542d901e0e36ee2d3193c4306a84f8cfa6
But I cannot see the llvm branch in my fork.

**Comment by Ebiroll** [comment]
From my side it looks as I have made a commit into your llvm branch.
https://github.com/marcusz/floyd/tree/llvm

**Pull request closed without merging**
